-- We are having 500 Apps and thier Application Domains and Server Details were emai will be stored
CREATE TABLE APPLICATIONS(APPLICATION_ID NUMBER PRIMARY KEY,APPLICATION_NAME VARCHAR2(100),APPLICATION_DOMAIN_NAME VARCHAR2(50),APPLICATION_EMAIL_SERVER_DNS VARCHAR2(500), SERVER_USER_NAME VARCHAR2(100),SERVER_PASSWORD VARCHAR2(80));

--EMAIl Users are Identifiedbased on Email Address. 
CREATE TABLE EMAIL_USERS (EMAIl_ADDRESS VARCHAR2(150) PRIMARY KEY, NAME1 VARCHAR2(100),PASSWORD1 VARCHAR2(50), GENDER VARCHAR2(1), DATE_OF_BIRTH DATE, APPLICATION_ID NUMBER REFERENCES APPLICATIONS(APPLICATION_ID));

--Attachments Type, Attachement Name,and Other Attachment details
CREATE TABLE ATTACHMENTS(ATTACHMENT_ID NUMBER PRIMARY KEY, ATTACHMENT_TYPE VARCHAR2(100),ATTACHMENT_NAME VARCHAR2(100),ATTACHMENT_EXTNATION VARCHAR2(100),ATTACHMENT_LOCATION VARCHAR2(1000), ATTACHMENT_SIZE VARCHAR2(1000));

--We are having Message Details like Subject, Body(Content),Message From,To,BCC,CC, and Attachments 
CREATE TABLE MESSAGES(MESSAGE_ID NUMBER PRIMARY KEY,MESSAGE_STATUS VARCHAR2(10), MESSAGE_SUBJECT VARCHAR2(1000),MESSAGE_CONTENT VARCHAR2(10000), MESSAGE_FROM  VARCHAR2(100), MESSAGE_TO VARCHAR2(100),MESSAGE_CC VARCHAR2(1000),ATTACHMENT_ID NUMBER REFERENCES ATTACHMENTS(ATTACHMENT_ID));
-- We are having Mail Box table to fillter the Mails by Inbox,Sent,Draft,Span,Deleted and its status by whter read them or not 
CREATE TABLE MAIL_BOX(MAIL_BOX_TYPE VARCHAR2(1000),MESSAGE_ID NUMBER REFERENCES MESSAGES(MESSAGE_ID));

DESC APPLICATIONS;
DESC EMAIL_USERS;
DESC ATTACHMENTS;
DESC MESSAGES;
DESC MAIL_BOX;
